### PR TITLE
Compiler Fix

### PR DESCRIPTION
**Pull request by vzrenggamani**
# Know Issues
1. Linux compiler will thrown error if we use `makeobj` from the repository.
2. Its too hard for compile `makeobj` by self.

# Temp fix
1. I have create self compiled makeobj from simutrans svn@8870 or latest stable version ( January, 13 2020)
2. I have upload it to the Google Storage Bucket for easier to use.
3. I'll modify to get the worked makeobj for the linux compiler from my google storage bucker

or

Upload worked makeobj as LFS object to the git instead of regular commit.

# Known Security issues
1. Anybody here wont take a risk to download from unknow source
2. Its too complicated

Reference #16

### CODE REVIEW

**Comment by vzrenggamani** [comment]
#17 #16

**Comment by Leartin** [comment]
Thank you, but I'm not sure this is a good idea.

If it's just a matter of the current makeobj not working, while your makeobj would work for all Linux versions, just put it in the repository as a replacement. I would not want a script to download something from wherever.
But is that really it? To my knowledge, the makeobj for Linux did not work on some systems due to missing dependencies. Can you really guarantee that yours works universally, and not just on your specific Linux?

**Comment by vzrenggamani** [comment]
nah, I am still figuring this out. It works on Linux Ubuntu 18.10 LTS which most of people using of it.

I am agree about downloading from unknow sources which i concern about it. I am just bypassing the security and compability for quick fix.

I would like to make an CI/CD for this repos and automatically create an nightly build. So the compilation done automatically.

**Comment by Flemmbrav** [comment]
Did you try to run the compile code with the makeobj that comes with the git right now, after compiling makeobj on your own?

**Comment by vzrenggamani** [comment]
> Did you try to run the compile code with the makeobj that comes with the git right now, after compiling makeobj on your own?

Yes, i did. I have attach the terminal log for the reference. But i'am also doesn't guarantee it will works widely in linux OSes.
[pak192-comic.log](https://github.com/Flemmbrav/Pak192.Comic/files/4059062/pak192-comic.log)

**Comment by Flemmbrav** [comment]
Yay! looks like it did work?
So the makeobj we have in the pakset is fine?

**Comment by vzrenggamani** [comment]
In some pc, it's fine, in the other PC it's broke up. Like leartin said, there must be libs missing.

**Comment by Leartin** [comment]
Prissi suggested to use a github action to compile makeobj and then run the compile script every time the repository changes. --> https://forum.simutrans.com/index.php/topic,17767.msg183507.html#msg183507
This means the regular user can always access a nightly pakset, while someone more involved likely already has their own makeobj anyway.
It does not currently work, since it does not fully compile makeobj in the first place (I only get makeobj-makeobj.o and makeobj-makeobj.d) but in testing I also tried just the part that calls the shell script with both the makeobj currently in the repository and later the one you compiled, both having the same issue you originally had.

So what did you do to fix the issue locally? Which libs did you install? Perhaps the same could be applied to the action, since that would be a convenient, permanent solution.

(My poor attempts can be found here: https://github.com/Leartin/Pak192.Comic/tree/Leartin-Action)

**Comment by vzrenggamani** [comment]
https://github.com/miyasakakoki/simu-docker 

I am just using this dockerimage to build the makeobj and also compile the pakset locally inside the docker.

In some cases, i forward it through my cloud build VM in the GCP

--

EDIT : 

I have try it myself using GitHub action and it seems passed the compiling.

https://github.com/vzrenggamani/Pak192.Comic/tree/githubaction-nightly

Github actions link : https://github.com/vzrenggamani/Pak192.Comic/commit/d86e9b93acb541a99870e844a346d316f05bede3/checks?check_suite_id=404294315

Releases : https://github.com/vzrenggamani/Pak192.Comic/releases/tag/refs%2Fheads%2Fmaster

**Comment by Flemmbrav** [comment]
I'm a bit confused on what to do now. As far as i am concerened the makeobj we have in the repo right now is fine by itself?

Plus, the aauto compile from github works too?

**Comment by Leartin** [comment]
Nah. The makeobj in the repo is not fine, as I could not pak via action using it - it only worked once I got the freshly compiled makeobj as a replacement.
But the goal was to provide the pakset, and that's completed with the automatic nightly. I do not think it's within the scope of the pakset to provide up-to-date makeobj.

**Comment by Flemmbrav** [comment]
Same, so I'd remove the manual compilers now? Shall i leave a scribt so people could do it manually if they add makeobj themselves?

**Comment by vzrenggamani** [comment]
I will agree with both of you.
pak192.comic github repo now has nighty build and we don't need to add makeobj to the repos.
Whenever someone wan't to do it manually, they can use provided docs how to manually compile the pakset.

Closing this PR for sure 👍

**Pull request closed without merging**
